name: Objective-C CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Install
      run: pod install
    - name: Build
      run: xcodebuild test -workspace tiff-ios.xcworkspace -scheme tiff-ios -destination 'platform=iOS Simulator,OS=latest,name=iPhone ${iphone_device}'
      env:
        iphone_device: 11
