name: Objective-C CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build
      run: |
        ls
        xcodebuild test -workspace tiff-ios.xcworkspace -scheme tiff-ios -destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11' ONLY_ACTIVE_ARCH=NO
